+++
title = "Download Libraries"
[menu.main]
    parent = "Libraries"
    name = "Download"
    url = "/libraries/download/"
    identifier = "libraries_download"
    weight = 10
+++

== Library Downloads

The official KiCad libraries are available for download at link:https://kicad.github.io[https://kicad.github.io]. Library data are provided as compressed archives of the individual libraries within the following categories:

* Schematic symbols: link:https://kicad.github.io/symbols[https://kicad.github.io/symbols]
* PCB footprints: link:https://kicad.github.io/footprints[https://kicad.github.io/footprints]
* 3D models: link:https://kicad.github.io/packages3d[https://kicad.github.io/packages3d]

Library data are updated weekly, and track the link:https://github.com/KiCad[KiCad GitHub repositories].

== GitHub Libraries

KiCad libraries are community contributed and hosted on GitHub at link:https://github.com/kicad[github.com/kicad]. If you wish to contribute to the libraries, refer to the link:/libraries/contribute/[contribution guide].

=== Library Repositories

The set of libraries corresponding to `v4.xx` of KiCad software are organised on GitHub as follows:

**Symbols**, **3D models** and **project templates** are stored together in the link:https://github.com/kicad/kicad-library[kicad-library] repository.

**Footprint** libraries are stored as link:https://github.com/kicad?&q=.pretty[individual repositories] with the `.pretty` extension.

=== Future of the Libraries

In conjunction with the KiCad v5 software release, the libraries will be reorganised into four separate repositories (on GitHub).

* `kicad-symbols` - Schematic symbol libraries
* `kicad-footprints` - PCB footprint libraries
* `kicad-packages3d` - 3D model data
* `kicad-templates` - Project templates

== Updating Library Data

Users who wish to keep their libraries up to date with the latest additions should link:https://help.github.com/articles/cloning-a-repository/[clone] the library repositories using Git. Tracking the library repositories using Git means that only the __changes__ to the libraries need to be downloaded, rather than retrieving the entire library set each time.