+++
brief = "Connector naming conventions"
+++

{{< fp_naming_header type="connector" >}}

== Conventions for Connectors

Connector footprints are extremely diverse and the naming conventions for connectors can be complicated. This section details some examples of naming schemes for various connector types. While there are variations between connectors, the general format for naming connectors is as follows:

{{< fp_code name="conn_basic" >}}

Notes:

. [`Series`] - a versatile field which could contain:
* Functional description (e.g. `USB`)
* Connector type (e.g. `PinHeader` or `TerminalBlock`)
* Industry standard (e.g. `DSUB-15`)
* Manufacturer specific series (e.g. `Hirose_DF13`)
. [`MPN`] (manufacturer part number) - uniquely identifies a connector according to that manufacturer's internal naming conventions
. [`Pin layout`] - dependent on the connector type
* Single row connectors: 1x[`number of pins`]
* Multi row connectors with equal number of pins in each row: [`number of rows`]x[`number of pins per row]`
* Other connectors: [`number of rows`]Rows_[`number of pins overall`]Pins
* Connectors for standardized interfaces do not need to include the pin configuration information (e.g. USB)
. Number format:
* [`number of rows`] number of rows no leading zero.
* [`number of pins per row`] and [`number of pins`] two digit number with leading zero. (can have more digits for connectors with > 99 pins)
. [`Pitch`] - if the connector standard does not imply the pin pitch, then this field is required
. [`Modifiers`] - multiple fields may be added here, detailing modifications or devations from the standard footprint design. Examples include:
* Pad size variation
* Drill size variation
. [`Orientation`] - The orientation of the connector with reference to the board plane

{{< klcimg_full_width src="connector_orientation" title="The orientation of connectors is determined by the plug direction." >}}

[start = 7]
. [`Options`] - Extra footprint options

In addition to these conventions, additional schemes are employed for specific connector types - these are detailed below.

=== Connectors for Specific Functions

Many connectors are designed for specific functions (e.g. USB, HDMI, SD-Card, etc). In these cases, specific naming conventions should be followed:

{{< fp_code name="conn_func" >}}

Notes:

. Some _examples_ of functional connector naming are provided below:
* `USB_Micro-B_Wuerth_614105150721_Vertical_CircularHoles`
* `HDMI_Micro-D_Molex_46765-2x0x`
* `MicroSD_Wuerth_WR-CRD_693072010801`
. In most cases, pin layout does not need to be explicitly specified

=== Connectors with Standardised Shape

Many connectors are provided by multiple manufacturers in an industry standard package or physical layout. These connectors should use the accepted industry naming at the beginning of the footprint name:

{{< fp_code name="conn_standard" >}}

Notes:

. The generic connector type [`Standard`] defines the shape of the connector
* e.g. `DSUB` `Tab` `Circular`

=== Generic Connector Types

Examples of generic arrayed connectors:

* PinHeader
* PinSocket
* TerminalBlock

{{< fp_code name="conn_generic" >}}

=== Manufacturer Specific Connectors

Manufacturer series connectors are those which are particular to a particular manufacturer standard.

{{< fp_code name="conn_manu" >}}

Notes:

. If the footprint is located in a library dedicated to a single manufacturer, then the `MAN` prefix is not required
