== 5.1.0 Stable Release

=== Installation
KiCad 5.1.0 is available in https://launchpad.net/~js-reynaud/+archive/ubuntu/kicad-5.1[PPA for KiCad: 5.1 releases ].

To install KiCad via the PPA, you can use the Software Manager:

1. Open the Software Manager.
2. Select 'Edit' -> 'Software Sources...'.
3. Open the 'Other Software' tab.
4. Click 'Add...', and enter the PPA address: `ppa:js-reynaud/kicad-5.1` and then click the 'Add Source' button.
5. When prompted insert the administrator user password.
6. Return to the Software Manager and view the Progress tab to see when the cache has finished updating.
7. Return to the Software Manager main screen, search for 'kicad', and install it.

The KiCad schematic library and docs are in separate packages. If you want either of these install kicad-library and kicad-doc respectively.

If you prefer to use the shell, you can enter these commands into a terminal:

[source,bash]
sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
sudo apt update
sudo apt install --install-suggests kicad

For Linux Mint you should use:

[source,bash]
sudo apt install --install-suggests --install-recommends kicad

This will perform a full installation of KiCad. If you don't want to install all packages you can use:

[source,bash]
sudo apt install kicad

If you don't do a "full installation" you should be interested to install also:

* kicad-libraries: a virtual package that will recommend you to install footprints, symbols, templates and 3D
* kicad-symbols, kicad-templates, kicad-footprints, kicad-packages3d: if you want to manually select what library to install.

Additionnal packages can be also installed according your language:

* kicad-locale-XX: locales for your language (XX is your contry code. see apt search kicad-locale to find available languages)
* kicad-doc-XX: documentation in your language. Same remark than kicad-locale-XX

=== Migration from legacy nightly build

Follow migration instructions on the 5.0 release

== 5.0.2 Stable Release

=== Installation

KiCad 5.0.2 is available in https://launchpad.net/~js-reynaud/+archive/ubuntu/kicad-5[PPA for KiCad: 5.0 releases].

To install KiCad via the PPA, you can use the Software Manager:

1. Open the Software Manager.
2. Select 'Edit' -> 'Software Sources...'.
3. Open the 'Other Software' tab.
4. Click 'Add...', and enter the PPA address: `ppa:js-reynaud/kicad-5` and then click the 'Add Source' button.
5. When prompted insert the administrator user password.
6. Return to the Software Manager and view the Progress tab to see when the cache has finished updating.
7. Return to the Software Manager main screen, search for 'kicad', and install it.

The KiCad schematic library and docs are in separate packages. If you want either of these install kicad-library and kicad-doc respectively.

If you prefer to use the shell, you can enter these commands into a terminal:

[source,bash]
sudo add-apt-repository --yes ppa:js-reynaud/kicad-5
sudo apt update
sudo apt install kicad

You can also install suggested package to have a full install:
[source,bash]
sudo apt install --install-suggests kicad

For Linux Mint you should use:

[source,bash]
sudo apt install --install-suggests --install-recommends kicad

If you don't do a "full installation" you should be interested to install also:

* kicad-libraries: a virtual package that will recommend you to install footprints, symbols, templates and 3D
* kicad-symbols, kicad-templates, kicad-footprints, kicad-packages3d: if you want to manually select what library to install.
* kicad-locale-XX: locales for your language (XX is your contry code. see apt search kicad-locale to find available languages)
* kicad-doc-XX: documentation in your language. Same remark than kicad-locale-XX

=== Migration from legacy nightly build

Users of the legacy nightly build have to remove KiCad packages before
trying to install version 5.0. The legacy nightly build will be always newer than
version 5.0.
To remove the legacy nightly build:

[source,bash]
sudo apt-get remove kicad kicad-footprints kicad-libraries
sudo apt-get remove kicad-symbols kicad-templates  kicad-packages3d
sudo apt-get remove kicad-doc-* kicad-locale-*
sudo add-apt-repository -r ppa:js-reynaud/ppa-kicad

Then perform the installation of the stable released as described above this section

== Nightly Development Builds
Nightly builds are provided in a separate installation directory. It is
possible to install nightly builds at the same time as a stable version (5.0 for example).

Nightly development builds are available in
https://launchpad.net/~js-reynaud/+archive/ubuntu/kicad-dev-nightly[js-reynaud's nightly PPA].
These provide the latest, unreleased preview of KiCad.
To install KiCad via the PPA, you can use the Ubuntu Software Manager:

1. Open the Software Manager.
2. Select 'Edit' -> 'Software Sources...'.
3. Open the 'Other Software' tab.
4. Click 'Add...', and enter the PPA address: `ppa:js-reynaud/kicad-dev-nightly` and then click the 'Add Source' button.
5. When prompted insert the administrator user password.
6. Return to the Software Manager and view the Progress tab to see when the cache has finished updating.
7. Return to the Software Manager main screen, search for 'kicad-nightly', and install it.

If you prefer to use the shell, you can enter these commands into a terminal:

[source,bash]
sudo add-apt-repository --yes ppa:js-reynaud/kicad-dev-nightly
sudo apt update
sudo apt install kicad-nightly
# You can also install debug symbols:
sudo apt install kicad-nightly-dbg
# Demo
sudo apt install kicad-nightly-demo
# and libraries
sudo apt install kicad-nightly-footprints kicad-nightly-libraries kicad-nightly-packages3d kicad-nightly-symbols kicad-nightly-templates

To launch nightly version of a kicad's binaries, you have to add "-nightly" to the
command name:

- kicad -> kicad-nightly
- pcbnew -> pcbnew-nightly
- eeschema -> eeschema-nightly
- ...


== Legacy nightly Development Builds

Legacy nightly build system is still available. It is available in
https://launchpad.net/~js-reynaud/+archive/ubuntu/ppa-kicad[js-reynaud's legacy nightly PPA].

To use it:

[source,bash]
sudo add-apt-repository ppa:js-reynaud/ppa-kicad
sudo apt-get update
sudo apt install kicad

CAUTION: This ppa don't allow you to install a stable version at the same time

== 4.0 old stable

KiCad 4.0 is still available in
https://launchpad.net/~js-reynaud/+archive/ubuntu/kicad-4[js-reynaud's
KiCad 4.0 PPA].

CAUTION: This version is not recommended for new designs

== Translations
If you want KiCad to be translated, you also need to install the dedicated localization package.
Run this command after replacing `XX` by your language code ('fr' for French for instance) :

[source,bash]
sudo apt install kicad-locale-XX

== Libraries and additional packages
If you want KiCad libraries you have to install the following
packages:

- kicad-libraries: a meta package for all libraries
- kicad-symbols: All symbols (installed by default)
- kicad-templates: Project templates (installed by default)
- kicad-footprints: All footprints (installed by default)
- kicad-packages3d: 3D for footprints (installed by default. Could be heavy to download)
- kicad-demo: demonstration projects (not installed by default)
- kicad-doc-XX: documentation. Replace `XX` by your language code ('fr' for French for instance)
- kicad-dbg: debug symbols. Usefull for bug tracking and developpers (not installed by default. Could be heavy to download)

To install kicad-demo for example:
[source,bash]
sudo apt install kicad-demo
