+++
title = "Debian"
iconhtml = "<div class='fl-debian'></div>"
weight = 10
+++

=== Debian Unstable (Sid)

Current Version: *4.0.5* (KiCad actual version)

The current upstream release 4.0.5 is available for Debian
https://packages.debian.org/sid/kicad[unstable/sid].

=== Debian Testing (Stretch)

Current Version: *4.0.5* (KiCad actual version)

The current upstream release 4.0.5 is available for Debian
https://packages.debian.org/stretch/kicad[testing/stretch] and

You can install it with the following commands in a terminal, otherwise you can
use the package manager you like:

[source,bash]
sudo apt-get update
sudo apt-get install kicad

Offline docs are available in seperate packages named for example
`kicad-doc-en`. You can search for them with _apt-cache_ for example

[source.bash]
apt-cache search kicad-doc

=== Debian Stable (Jessie)

Jessie-Backport Version: *4.0.5* (KiCad actual version)

or

Jessie Stable Release Version: *bzr4027* (KiCad stable release 2014)

The 2014 stable release bzr4027 of KiCad is available in the official Debian
repositories for https://packages.debian.org/jessie/kicad[stable/jessie].
It is not recommended for new designs. Please use the packages from the
backport repository for actual versions. Follow the instructions on the
https://wiki.debian.org/Backports[Debian Wiki] to add the Backport repository
to your sources and install the KiCad packages from
https://packages.debian.org/jessie-backports/kicad[jessie-backports].

=== Debian Old-Stable (Wheezy)

Current version: *bzr3261* (KiCad stable release 2012), or *bzr4027* via
Backports

Unfortunately there is only release bzr3261 from 2012 in the old-stable
repository and version bzr4027 (this is the same as on current stable) in the
old-stable-backport repository. As for Debian stable, it's recommend for new
designs. So you better upgrade your Debian installation to Debian Stable
(Jessie) and use the version there from backport.

=== Build from Source
You can find the instructions to build from source
link:http://docs.kicad-pcb.org/doxygen/md_Documentation_development_compiling.html#build_linux[here].
If you have a running Debian stable with actual packages from Backports or you
running a testing/sid release you can compile your own version of KiCad. *Note*,
the use of Spice features isn't possible now, even in testing/unstable as
the ngspice package isn't providing the needed libngspice library. If you need
Spice related support in KiCad you will need to build a modified ngspice
package. See this link:http://https://bugs.debian.org/834335[bug report] for
further information.

Ensure you have installed some build dependencies at least before you try to
start own builds:

[source.bash]
sudo apt-get install doxygen libboost-context-dev libboost-dev \
libboost-system-dev libboost-thread-dev libcairo2-dev libcurl4-openssl-dev \
libgl1-mesa-dev libglew-dev libglm-dev liboce-foundation-dev liboce-ocaf-dev \
libssl-dev libwxbase3.0-dev libwxgtk3.0-dev python-dev python-wxgtk3.0-dev \
swig wx-common
