+++
title = "Debian"
iconhtml = "<div class='fl-debian'></div>"
weight = 10
+++

== Debian Unstable (Sid)

{{< repology debian_unstable >}}


The current upstream release is available for Debian
https://packages.debian.org/sid/kicad[unstable/sid].

For installing please read further.

== Debian Testing (Buster)

Currently not available until KiCad 5.0 is released.

== Debian Stable (Stretch)

{{< repology debian_stable_backports >}}

{{< repology debian_stable >}}

The release 4.0.5 is available for Debian
https://packages.debian.org/stretch/kicad[stable/stretch], the backported
version 4.0.7 is available in
https://packages.debian.org/stretch-backports/kicad[stretch-backports].

You can install it with the following commands in a terminal, otherwise you can
use any of the package managers you like:

[source,bash]
sudo apt update
sudo apt install kicad

Offline docs are available in seperate packages named for example
`kicad-doc-en`. You can search for them with _apt_ or _apt-cache_ for example.

[source.bash]
apt search kicad-doc
# or alternatively if you are on wheezy
apt-cache search kicad-doc

== Debian Old-Stable (Jessie)

Jessie Backport Version: *4.0.7* (KiCad actual version)

or

Jessie Release Version: *bzr4027* (KiCad stable release 2014)

The 2014 stable release bzr4027 of KiCad is available in the official Debian
repositories for https://packages.debian.org/jessie/kicad[oldstable/jessie].
It is not recommended for new designs. Please use the packages from the
backport repository for actual versions. Follow the instructions on the
https://wiki.debian.org/Backports[Debian Wiki] to add the Backport repository
to your sources and install the KiCad packages from
https://packages.debian.org/jessie-backports-sloppy/kicad[jessie-backports-sloppy].

== Debian Old-Old-Stable (Wheezy)

Wheezy Backport Version: *bzr4027*

or

Wheezy Release Version: *bzr3261* (KiCad stable release 2012)

Unfortunately there is no newer version for the Wheezy release available so you
need to stay with bzr3261 from 2012 in the old-old-stable repository or version
bzr4027 from the
https://packages.debian.org/wheezy-backports/kicad[wheezy-backport] repository
then. As for Debian old-stable, they are not recommended for new designs. So
you really better upgrade your Debian installation at least to Debian
Old-Stable (Jessie) or better to Stable (Stretch) and use the version there
from backport.

== Build from Source
You can find the instructions to build from source
link:http://docs.kicad-pcb.org/doxygen/md_Documentation_development_compiling.html#build_linux[here].
If you have a running Debian stable with actual packages from Backports or you
running a testing/sid release you can compile your own version of KiCad. *Note*,
the use of Spice features isn't possible now, even in testing/unstable as
the ngspice package isn't providing the needed libngspice library. If you need
Spice related support in KiCad you will need to build a modified ngspice
package. See this link:https://bugs.debian.org/834335[bug report] for
further information.

Ensure you have installed some build dependencies at least before you try to
start own builds:

[source.bash]
sudo apt install cmake doxygen libboost-context-dev libboost-dev \
libboost-system-dev libboost-test-dev libcairo2-dev libcurl4-openssl-dev \
libgl1-mesa-dev libglew-dev libglm-dev liboce-foundation-dev liboce-ocaf-dev \
libssl-dev libwxbase3.0-dev libwxgtk3.0-dev python-dev python-wxgtk3.0-dev \
swig wx-common
