+++
title = "Fedora"
iconhtml = "<div class='fl-fedora'></div>"
weight = 20
+++

== Stable Release
In general, latest Fedora releases ship the stable versions KiCad as they are
released.

To install the most recent stable KiCad package on Fedora simply search for it
in the Software app or open a terminal and run the following command:

[source,bash]
dnf install kicad

In case the latest KiCad release is not yet available in the updates repository,
chances are you'll find it in the testing repository. Run the following command
to install a testing package:

[source,bash]
dnf --enablerepo=updates-testing install kicad

== Nightly Development Builds

Nightly development builds for Fedora are available via the
link:https://copr.fedorainfracloud.org/coprs/g/kicad/kicad/[copr build
service].

This build can be installed on Fedora with:

----
dnf copr enable @kicad/kicad
dnf install kicad
----

The `@kicad/kicad` repository replaces the `mangelajo/kicad` repository that was
previously used to deliver the development builds. If you've previously used it
you can safely remove it now:

----
dnf copr remove mangelajo/kicad
----

If you don't have copr install with:

----
dnf install dnf-plugins-core
----
