+++
title = "Linux Mint"
iconhtml = "<div class='fl-linuxmint'></div>"
weight = 11
+++


:icons: fonts
:iconsdir: /img/icons/

== 5.0.0 Stable Release

KiCad 5.0.0 is available in https://launchpad.net/~js-reynaud/+archive/ubuntu/kicad-5[js-reynaud's KiCad 5.0 PPA].

To install KiCad via the PPA, you can use the Software Manager:

1. Open the Software Manager.
2. Select Edit → Software Sources.
3. Open the 'PPAs' tab.
4. Click 'Add a new PPA', and enter the PPA address: `ppa:js-reynaud/kicad-5`
5. Click 'Update the cache'
6. Return to the Software Manager main screen, search for 'kicad', and install it.

The KiCad schematic library and docs are in separate packages. If you want either of these install kicad-library and kicad-doc respectively.

If you prefer to use the shell, you can enter these commands into a terminal:

[source,bash]
sudo add-apt-repository --yes ppa:js-reynaud/kicad-5
sudo apt-get update
sudo apt-get install kicad

== Nightly Development Builds
Nightly development builds are available in https://code.launchpad.net/~js-reynaud/+archive/ubuntu/ppa-kicad[js-reynaud's PPA].
These provide the latest, unreleased preview of KiCad.
To install KiCad via the PPA, you can use the Software Manager:

1. Open the Software Manager.
2. Select Edit → Software Sources.
3. Open the 'PPAs' tab.
4. Click 'Add a new PPA', and enter the PPA address: `ppa:js-reynaud/ppa-kicad`
5. Click 'Update the cache'
6. Return to the Software Manager main screen, search for 'kicad', and install it.

If you prefer to use the shell, you can enter these commands into a terminal:

[source,bash]
sudo add-apt-repository --yes ppa:js-reynaud/ppa-kicad
sudo apt-get update
sudo apt-get install kicad

== 4.0 Stable
CAUTION: This version is not recommended for new designs

KiCad 4.0 is still available in https://launchpad.net/~js-reynaud/+archive/ubuntu/kicad-4[js-reynaud's KiCad 4.0 PPA]
