+++
title = "Linux Mint"
iconhtml = "<div class='fl-linuxmint'></div>"
weight = 11
+++

=== Development Builds
Daily builds are available in https://code.launchpad.net/~js-reynaud/+archive/ubuntu/ppa-kicad[js-reynaud's PPA].
These provide the latest, unreleased preview of KiCad.
To install KiCad via the PPA, you can use the Software Manager:

1. Open the Software Manager.
2. Select Edit → Software Sources.
3. Open the 'PPAs' tab.
4. Click 'Add a new PPA', and enter the PPA address: `ppa:js-reynaud/ppa-kicad`
5. Click 'Update the cache'
6. Return to the Software Manager main screen, search for 'kicad', and install it.

If you prefer to use the shell, you can enter these commands into a terminal:

[source,bash]
sudo add-apt-repository ppa:js-reynaud/ppa-kicad
sudo apt-get update
sudo apt-get install kicad

=== Old Stable
The most recent full release of KiCad is old, and not recommended for new projects.
If you want it, Old Stable is the official repository.
Search for `KiCad` in the Software Manager or execute the following in a terminal:

[source,bash]
sudo apt-get install kicad
