+++
title = "openSUSE"
iconhtml = "<div class='fl-opensuse'></div>"
weight = 20
+++

=== 4.0.0 Pre-release

A pre-release "release candidate" is available for KiCad 4.0.0.

Current Version: *4.0.0 RC1*

This pre-release version is available in https://launchpad.net/~js-reynaud/+archive/ubuntu/kicad-4[js-reynaud's KiCad 4.0 PPA] is available in the link:http://software.opensuse.org/download.html?project=electronics&package=kicad[opensuse electronics repository]. 
See the link:https://build.opensuse.org/package/show/electronics/kicad[OBS page] for details.

New KiCad packages do not have the _kicad-library_ subpackage. It is possible to use the built-in GUI downloader or the kicad-library-install.sh script from the _kicad-library-install_ subpackage.

Please report openSUSE-specific bugs via "Report Bug" button on OBS page.

=== Development Builds
KiCad daily builds for openSUSE are available as _kicad-unstable_ in the link:http://software.opensuse.org/download.html?project=electronics&package=kicad-unstable[opensuse unstable electronics repository]. 
See link:https://build.opensuse.org/package/show/electronics/kicad-unstable[OBS page] for details.

New KiCad packages do not have the _kicad-library_ subpackage. It is possible to use the built-in GUI downloader or the kicad-library-install.sh script from the _kicad-library-install_ subpackage.

Please report openSUSE-specific bugs via the "Report Bug" button on OBS page.
