+++
title = "MacOS"
iconhtml = "<div><i class='fa fa-apple'></i></div>"
weight = 2
+++

KiCad is known to work on Mac OS X 10.11 through macOS 10.13.  It may work on later versions, and if it does not, it is a bug and will be fixed.

*kicad-unified* is the default package that most people should install.  *kicad-unified* contains everything: the KiCad suite, documentation, schematic symbols, footprints, translations, templates, demos, and 3D models.

== Stable Release

Current Version: *5.0.0*

- http://downloads.kicad-pcb.org/osx/stable/kicad-unified-5.0.0-1.dmg[KiCad]

== Nightly Development Builds

The _nightly_ builds are snapshots of the codebase at a specific time. They may contain more bugs than usual, although we try our best.  If you need to test features in active development, the nightly can be faster to download, and extras can be used to turn a nightly into a full install. 

- *kicad-nightly* does not contain the 3D models.  It contains the KiCad suite, documentation, schematic symbols, footprints, translations, templates, and demos.

- *kicad-extras* contains the 3D models.

http://downloads.kicad-pcb.org/osx/nightly/
