+++
title = "OS X"
iconhtml = "<div><i class='fa fa-apple'></i></div>"
weight = 2
+++

=== 4.0.0 Pre-release

A pre-release "release candidate" is available for KiCad 4.0.0.

Current Version: *4.0.0 RC2*

This pre-release version is available as dmg files seperated in two
dmg files.

The kicad.dmg files include the KiCad suite, documentation, schematic symbols, and some templates.  It gets footprints from the internet.

kicad-extras.dmg contains the footprints and all the instructions you need for making printed circuit board layouts while offline.

 - http://downloads.kicad-pcb.org/osx/stable/kicad-4.0.0-rc2-1.dmg[KiCad main package]
 - http://downloads.kicad-pcb.org/osx/stable/kicad-extras-4.0.0-rc2-1.dmg[KiCad extras]

You usually want to install both disk images.

=== Recent Builds
Nightly builds of KiCad for OS X are available on http://downloads.kicad-pcb.org/osx/, built by Adam Wolf.  KiCad is supported on OS X 10.7 through OS X 10.11.

These are the "nightly" builds.  This means they are snapshots of the codebase at that time, and may contain even more bugs than usual, although we try our best.

=== Build from Source
You can find the instructions to build from source link:http://kicad-pcb.org/contribute/build-osx/[here]. 

Do not use the https://github.com/KiCad/KicadOSXBuilder[KicadOSXBuilder] as it is outdated. 
