+++
title = "MacOS"
iconhtml = "<div><i class='fa fa-apple'></i></div>"
weight = 2
+++
:icons: fonts
:iconsdir: /img/icons/

KiCad is known to work on Mac OS X 10.11 through macOS 10.14.  It may work on newer versions.  If it does not, it is a bug and will be fixed.   If you are going to use macOS 10.14, use the download with 10_14 in its name. If you are going to use 10.11-10.13, use the download without 10_14 in its name.

*kicad-unified* is the default package that most people should install.  *kicad-unified* contains everything: the KiCad suite, documentation, schematic symbols, footprints, translations, templates, demos, and 3D models.


== Stable Release

Current Version: *5.0.2*

[NOTE]
For the time being there have been some packaging related issues with
5.0.2 for macOS, so please get 5.0.1 from
https://kicad-downloads.s3.cern.ch/index.html?prefix=osx/stable/[https://kicad-downloads.s3.cern.ch/index.html?prefix=osx/stable/]
or hold back upgrading on macOS.

//- For macOS 10.14: https://kicad-downloads.s3.cern.ch/osx/stable/kicad-unified-5.0.2-10_14.dmg[KiCad] http://www2.futureware.at/~nickoe/kicad-downloads-mirror/osx/stable/kicad-unified-5.0.2-10_14.dmg[[mirror]]
//- For macOS 10.11-10.13: https://kicad-downloads.s3.cern.ch/osx/stable/kicad-unified-5.0.2.dmg[KiCad] http://www2.futureware.at/~nickoe/kicad-downloads-mirror/osx/stable/kicad-unified-5.0.2.dmg[[mirror]]

== Nightly Development Builds

The _nightly_ builds are snapshots of the codebase at a specific time. They may contain more bugs than usual, although we try our best.  If you need to test features in active development, the nightly can be faster to download, and extras can be used to turn a nightly into a full install.

- *kicad-nightly* does not contain the 3D models.  It contains the KiCad suite, documentation, schematic symbols, footprints, translations, templates, and demos.

- *kicad-extras* contains the 3D models.

[NOTE]
The nightlies for macOS are probably not avialable for some time, but
the goal is to get them available ASAP.

https://kicad-downloads.s3.cern.ch/index.html?prefix=osx/nightly/
