+++
title = "Source Code"
iconhtml = "<div><i class='fa fa-code'></i></div>"
weight = 100
+++
:icons:
:iconsdir: /img/icons/


The most recent source code for KiCad can be downloaded from the
https://gitlab.com/kicad/code/kicad[gitlab repository] or the
https://github.com/KiCad/kicad-source-mirror[github mirror].

This source contains the most recent patches and is useful for
debugging and testing. If you build KiCad from source consider
joining the https://launchpad.net/~kicad-developers/[developer mailing
list] to post your improvements and
https://gitlab.com/kicad/code/kicad/issues[bug-fixes to issues].

Other than the source code itself there are some other distibruted
elements that make up the full KiCad package, which is the KiCad
documentation (kicad-doc), the user interface translations
(kicad-i18n), and the schematic, footprint, 3D model libraries and
project templates.

== Stable Release

Current Version: *5.1.6*

Tarballs intended to be used by packagers:

* link:https://gitlab.com/kicad/code/kicad/-/archive/5.1.6/kicad-5.1.6.tar.gz[Source code]
* link:https://kicad-downloads.s3.cern.ch/docs/kicad-doc-5.1.6.tar.gz[Precompiled docs], https://gitlab.com/kicad/services/kicad-doc/-/tags/5.1.6[doc sources]
* link:https://gitlab.com/kicad/code/kicad-i18n/-/archive/5.1.6/kicad-i18n-5.1.6.tar.gz[i18n (translations)]
* link:https://github.com/KiCad/kicad-symbols/releases/tag/5.1.6[symbols]
* link:https://github.com/KiCad/kicad-footprints/releases/tag/5.1.6[footprints]
* link:https://github.com/KiCad/kicad-packages3D/releases/tag/5.1.6[packages3D]
* link:https://github.com/KiCad/kicad-templates/releases/tag/5.1.6[templates]

As a packager, please work to enable all the build options, that is
all the scripting options, OCC (prefered) or OCE, and ngspice. With recent
versions of ngspice and wxPython Phoenix this should be easily
possible on recent distributions

Due to API instability in the Boost.Context library, KiCad 5 ships with
a replacement implementation, which is partially written in assembler
language. Because of this, several platforms may fail to compile.

== Building KiCad

Instructions can be found in compiling.md which is located in the
kicad source code under `/Documentation/development` folder.

Alternatively, you can view it online here:
link:http://docs.kicad-pcb.org/doxygen/md_Documentation_development_compiling.html[Building
KiCad from Source]

