+++
title = "Ubuntu"
iconhtml = "<div class='fl-ubuntu'></div>"
weight = 1
+++

== 4.0.7 Stable Release

KiCad 4.0.7 is available in https://launchpad.net/~js-reynaud/+archive/ubuntu/kicad-4[js-reynaud's KiCad 4.0 PPA].

To install KiCad via the PPA, you can use the Software Manager:

1. Open the Ubuntu Software Manager.
2. Select 'Edit' -> 'Software Sources...'.
3. Open the 'Other Software' tab.
4. Click 'Add...', and enter the PPA address: `ppa:js-reynaud/kicad-4` and then click the 'Add Source' button.
5. When prompted insert the administrator user password.
6. Return to the Software Manager and view the Progress tab to see when the cache has finished updating.
7. Return to the Software Manager main screen, search for 'kicad', and install it.

The KiCad schematic library and docs are in separate packages. If you want either of these install kicad-library and kicad-doc respectively.

If you prefer to use the shell, you can enter these commands into a terminal:

[source,bash]
sudo add-apt-repository --yes ppa:js-reynaud/kicad-4
sudo apt update
sudo apt install kicad

== Nightly Development Builds
Nightly development builds are available in https://code.launchpad.net/~js-reynaud/+archive/ubuntu/ppa-kicad[js-reynaud's PPA].
These provide the latest, unreleased preview of KiCad.
To install KiCad via the PPA, you can use the Ubuntu Software Manager:

1. Open the Ubuntu Software Manager.
2. Select 'Edit' -> 'Software Sources...'.
3. Open the 'Other Software' tab.
4. Click 'Add...', and enter the PPA address: `ppa:js-reynaud/ppa-kicad` and then click the 'Add Source' button.
5. When prompted insert the administrator user password.
6. Return to the Software Manager and view the Progress tab to see when the cache has finished updating.
7. Return to the Software Manager main screen, search for 'kicad', and install it.

If you prefer to use the shell, you can enter these commands into a terminal:

[source,bash]
sudo add-apt-repository --yes ppa:js-reynaud/ppa-kicad
sudo apt update
sudo apt install kicad

== Old Stable
The so called "old stable" is the kicad version before the version 4.0
series. It is not recommended for new projects. Please use the new
stable release from the PPA if you are on an older ubuntu release.

== Translations
If you want KiCad to be translated, you also need to install the dedicated localization package.
Run this command after replacing `XX` by your language code ('fr' for French for instance) :

[source,bash]
sudo apt install kicad-locale-XX
