KiCad Website Source
====================

This the source for the new KiCad website, anno 2015.

LICENSE
=======

The kicad-website repository is dual licensed. 
You may distribute it and/or modify it under the terms of either
the GNU General Public License (http://www.gnu.org/licenses/gpl.html),
version 3 or later, or the Creative Commons Attribution License
(http://creativecommons.org/licenses/by/3.0/), version 3.0 or later.

== Prerequisites
You will need these packages:

- http://gohugo.io/[hugo] version 0.30 (you must use this version!)
- https://www.ruby-lang.org[ruby] (to use asciidoctor)
- http://asciidoctor.org/[asciidoctor]

Using asciidoctor is a requirement, because the original asciidoc
runs into trouble parsing the adoc files with TOML headers in them.
asciidoctor also has a few extra features for web pages. 

== Testing

Execute the hugo command in the repository root to build and serve the
files for development:

----
hugo server -w -v
----

Observe the console output as it will tell you the address where the
page is accessible in a browser.  The -w flag tells it to watch the
filesystem for changes to rebuild automatically. Also, the page in the
browser will autorefresh once the rebuild completes successfully.

== Contributing
Please read the link:CONTRIBUTING.adoc[CONTRIBUTING Guidelines]
