KiCad Website Source
====================

This the source for the new KiCad website, anno 2015.


== Prerequisites
You will need these packages:

- http://gohugo.io/[hugo]
- https://www.ruby-lang.org[ruby] (to use asciidoctor)
- http://asciidoctor.org/[asciidoctor]

Using asciidoctor is a requirement, because the original asciidoc
runs into trouble parsing the adoc files with TOML headers in them.
asciidoctor also has a few extra features for web pages. 

== Testing

Execute the hugo command in the repository root to build and serve the files for development:

----
hugo server -w -v
----

Observe the console output as it will tell you the address where the page is accessible in a browser.
The -w flag tells it to watch the filesystem for changes to rebuild automatically. Also, the page in the browser will autorefresh once the rebuild completes successfully.

== Adding new pages

The desired format for new pages is asciidoc(.adoc) to keep inline with the KiCad documentation repository.
Do not use markdown even though that is hugo's preferred format.

HTML pages are allowed if special formatting is required (i.e. downloads page).

If the new page contains content that you cut out of some old page, make sure the old page includes a link to the new page.
We want people who bookmarked that old page to be able to find the content at the new page, because
http://www.w3.org/Provider/Style/URI[Cool URIs don't change].

== Adding images
Ensure your images go into a folder in /static/img that makes sense. General stuff can stay in that folder. Grouped content such as screenshots, made with KiCad, frontpage, etc should go into the respective folder (or make a new one). Try and keep image sizes reasonable. Use JPG instead of PNG if you must to get image file sizes if it makes sense.

== "Dynamic" content
We are using a static site generator so we do not have the ability for scripted dynamic content.
Avoid having content that needs to be "frequently" updated unless you are volunteering to maintain it for the forseeable future. An example of "dynamic" content would be a list of "recent bugs".
