+++
title = "File Formats"
[menu.main]
    parent = "Help"
    name   = "File Formats"
weight = 50
+++


KiCad writes all files in human readable ASCII. This makes
manipulation by hand and scripting very easy. The following is a
listing on what the different files are used for.

=== Native file formats

The `.sch`, `.lib`, `.brd`, `.kicad_pcb` and `.kicad_wks` file formats are link:http://bazaar.launchpad.net/~kicad-developers/kicad/doc/view/head:/doc/help/file_formats/file_formats.pdf[specified in this PDF] (click on "download file"). The other file format documentation is _Work In Progress_.

* `.pro`: project file. Holds parameters that apply to the entire project (schematic and PCB layout).

** `-save.pro`: ... backup of the project file.

* `.sch`: schematic file.

* `.lib`: schematic symbols library file.

** `-cache.lib`: ... a local copy of all the symbols used in the corresponding schematic, so that when the folder containing a KiCad project is copied to a different PC, the schematic can still be opened and printed and will still look the same as the original draughtsperson intended - even if that other PC does not have those symbols in its main libraries (or has symbols that coincidentally have the same name but are completely different).

** `-rescue.lib`: ... copies of conflicting/missing schematic symbols.

* `.mod`: legacy footprint module file (Obsolete, can only be read).

* `.pretty`: footprint library folders. The folder itself is the library.

* `.kicad_mod`: footprint files, containing one footprint description each.
      
* `.000`: ^*^ temporary file.

* `.bak`: backup of schematic file.

* `.brd`: legacy PCB layout file.

* `.kicad_pcb`: the new PCB layout file.

** `-save.kicad_pcb`: ... backup of the PCB Layout file.

* `.cmp`: parts-to-module assignments file.

* `.csv`: commonly used when exporting BOM file.

* `.dcm`: holds descriptions, aliases and keywords for library symbols.

* `.net`: ^*^: netlist in "Pcbnew"; format ... can be regenerated by viewing the schematic file and clicking the "Netlist generation" button.

* `fp-lib-table`: Footprint library list (_footprint libraries table_): list of footprint libraries (various formats) which are loaded by the board or the footprint editor or CvPcb.

* `.kicad_wks`: The page layout description files, for people who want a worksheet with a custom look.

* `.rpt`: report file, for documentation.

* `.gbr`: Gerber output files for manufacturing.

* `.drl`: Gerber drill file for manufacturing.

* `.pos`: position files (ASCII format), for automatic insertion machines.

* `.wrl`: VRML 3D model used in the 3D viewer to represent parts.

KiCad uses a few temporary file formats internally. The files it creates with these extensions (marked above with "^*^" ) can be excluded from version control software since they can be automatically regenerated from the source files when necessary.

=== Dedicated file formats

KiCad writes and reads some file formats dedicated to certain operation in collaboration with tools external to KiCad.

* `.idf`: IDFv3 files used to generate lightweight 3D model exports for the mechanical CAD designer of the board and parts.

* `.wings`: 3D model editable by link:http://www.wings3d.com/[Wings3D], used to generate the `.wrl` files.
      
* `.svg`: plot files (svg format), for documentation.

* `.ps`: plot files (postscript), for documentation.

* `.dxf`: plot files (dxf format), for documentation.

* `.plt`: plot files (HPGL format), for documentation.

* `.dsn`: SPECCTRA DSN file for autorouters (like link:http://sourceforge.net/projects/qautorouter/develop[QAutorouter],
link:http://www.freerouting.net/[FreeRouting]).

* `.ses`: SPECCTRA session files from autorouters (like link:http://sourceforge.net/projects/qautorouter/develop[QAutorouter],
link:http://www.freerouting.net/[FreeRouting]).

* `.cad`: GenCAD used for circuit testing by the assembly house.

=== Other formats used by the KiCad project

* `.pdf`: All the help documentation intended to be read by KiCad users is in "'.pdf'" format.

* EDIF (_Electronic Design Interchange Format_) netlist format.
link:https://en.wikipedia.org/wiki/EDIF[Wikipedia]
      
* `.png`: The link:http://www.w3.org/Graphics/PNG/[W3C recommended] portable network graphics format is a
good format for posting a section of a schematic (or a section of a PCB layout) to a web page, so people can see it immediately
in a web browser without manually "downloading" or "installing" anything.
      
