+++
title = "Getting Started"
[menu.main]
    parent = "Help"
    name   = "Getting Started"
weight = 1
+++

:icons: fonts
:iconsdir: /img/icons/

A full link:/help/documentation/#_getting_started[Getting Started guide] is included in the KiCad documentation, in multiple languages.
This covers the process of creating and completing a simple project.
We recommend that all new users read this first, in order to learn the basics.

== Quick KiCad Summary

This is a quick summary of how KiCad functions. More details can be found in the link:/help/documentation/[full documentation].

=== Libraries

KiCad uses two separate types of library: symbols (`.lib`) and footprints (`.pretty`). 
Symbols are used to draw the schematic.
Once symbols have been placed into the schematic, footprints
are assigned to them, and then these are used to
lay out the circuit board.

This means that you can assign whichever footprint suits your design without
having to create a unique schematic symbol. If you need to change a footprint during
board layout, simply update the assigned footprint, import it into the PCB, and you can continue designing your board.

==== Symbols

The schematic symbol libraries (`.lib`) used are listed in the
project file (`.pro`), which is created from a template when you start a new project.
Note that the libraries themselves are not contained in the project, only links to them.
When you share a project, you should at least keep the library cache (`-cache.lib`) with it, to ensure that others can see your symbols.

==== Footprints

It is recommended to use the 'Footprint Libraries Wizard' to download the official KiCad footprint files from GitHub.
This is the easiest way to get and update the official KiCad footprint libraries.
When creating your own footprint library files (`.pretty`) they can be edited from 'pcbnew'. Local libraries can be added to your system using the 'Footprint Libraries Manager'.

=== Basic Workflow

The basic workflow in KiCad is:

1. Create a project.
2. Create a schematic with 'eeschema'.
3. Assign footprints to symbols and generate the netlist.
4. Create a board with 'pcbnew', importing the netlist from 'eeschema'.
5. Test the board using the 'Design Rule Check'.
6. Generate production files.

It's possible to open both schematic and PCB files outside of the project manager, but this
might result in unexpected results since the project
manager configures the working environment for the other
tools. This workflow variant is not recommended.

TIP: If you need to share the project, use the
archive option in the file menu.
All files needed to open the project will be added
to the archive.
