+++
title = "Known System Related Issues"
aliases = [ "/post/known-system-related-issues/" ]
[menu.main]
    parent = "Help"
    name   = "Known System Related Issues"
  weight = 50
+++
:toc: macro
:toc-title:

toc::[]

This page is just a small note on some "weird" issues that have been
experienced with KiCad in relation to the systems that it runs on. This
means that this page does not describe KiCad functional bugs.

== All Platforms

=== High DPI Screens

KiCad is configured to automatically detect the proper scaling factor for
displaying the editor canvas on the screen by default. If the canvas only uses
1/4 of the screen and there is a constant offset between the cursor and
crosshairs, check to ensure that automatic canvas scaling is enabled on the
common settings page of the Preferences dialog.

There are some known issues that can cause the canvas to not automatically scale
properly, primarily on Linux installations (see https://bugs.launchpad.net/kicad/+bug/1841423[Launchpad Bug #1841423]
and https://gitlab.com/kicad/code/kicad/issues/54[GitLab Bug #54]).
To fix this, disable the automatic canvas scaling in the preferences
window and enter a custom scale factor. In most cases a scaling factor
of 2 seems to fix the issue.

Toolbar icons may also appear smaller on high DPI screens, but their size
can be scaled in the preferences window as well.

Menu items may have inconsistent vertical sizing, causing the bottom part of
the text to be cutoff. Disabling "Show icons in menus" in the Preferences
dialog will make all menu items a uniform height and fix the cutoff text
(see https://gitlab.com/kicad/code/kicad/issues/3785[GitLab Bug #3785]).

The grid dots may be difficult to see due to their smaller size on
these displays. On the modern canvas, their size can be increased
in the preferences window (see https://gitlab.com/kicad/code/kicad/issues/444[GitLab Bug #444]).


=== Legacy Canvas and wxGTK

The legacy canvas has problems with wxWidgets 3.0 built with GTK3,
this combination is usually called wxGTK on various package
distributions. Don't be confused when you see wxGTK 3.0.0 in your
package manager, this is usually referring to the wxWidgets version,
and not whether or not it is built against GTK3.

It has been seen that Fedora 20, 21 and 22, builds against GTK3.
The problem manifests in eeschema  with slow zooming, and the graphics
are not quite exact (try looking at the grid dots). And in pcbnew, the
canvas does not really draw properly at all.

On newer fedora builds they ship a wxwidgets compatability package, it
is called wxGTK in contrast to wxGTK3 which uses GTK3. The same
applies for archlinux, there you need the package wxgtk2. The packages
can coexist.


=== Bad Graphics Cards

There are a few older cards that seem to not behave properly with the
OpenGL canvas used in the new GAL canvas.
The list below includes the faulty cards identified thus far:

- Intel Graphics Media Accelerator (GMA) 4500M / Windows 7 64bit / crash
on startup (https://bugs.launchpad.net/kicad/+bug/1473786)
- ATI Hawaii XT [Radeon R9 290X] + 4K display + fglrx driver / Ubuntu
14.04 LTS / flashes when the rendering area is too big
(https://bugs.launchpad.net/kicad/+bug/1492117)
- ATI RV370 [Radeon X300 SE] + radeon driver / Xubuntu 14.04.1 / does
not display line rounded line ends
(https://bugs.launchpad.net/kicad/+bug/1498970)


=== Boost minimum version
There have previously been problems with bugs in the boost libraries.
A minimum version of boost 1.56 is currently required as it has fixes the majority of
bugs previously encountered.

== Linux

=== Radeon Graphics

Some users with Radeon graphics have been experiencing problems with
slow rendering in gerbview and eeschema.
https://bugs.launchpad.net/kicad/+bug/1003859[Some]
https://bugs.launchpad.net/kicad/+bug/1186813[bugs] have been opened related to Radeon cards.
The solution seems to be require changing an Xorg setting which is either `Option "EXAPixmaps" "off"` or `Option "ShadowPrimary"` (see the bug reports for details).

=== Intel Graphics
Some users with Intel HD Graphics are having rendering problems with
the legacy canvas (and eeschema). It has been reported on at least a
laptop with a Intel Pentium P6000 processor and integrated graphics.

A solution is to configure Xorg. Create a Xorg configuration file
`/usr/share/X11/xorg.conf.d/20-intel.conf`, with the follow
information:

  Section "Device"
    Identifier  "Intel Graphics"
    Driver      "intel"
  EndSection


=== wxGTK 3.0.1

Version 3.0.1 of wxWidgets for Linux (with GTK) can crash when running
DRC. This is an issue not seen in wxGTK 3.0.2, so it seems to be fixed
upstream. More details can be found in
link:https://bugs.launchpad.net/kicad/+bug/1442909[Bug# 1442909].

=== Wayland
It is known that KiCad does not work well under Wayland. There are a number
of known issues with wxWidgets and Wayland.  link:https://trac.wxwidgets.org/query?status=!closed&keywords=~Wayland[See the wxWidgets bug tracker for details].

KiCad requests the XWayland compatibility layer when starting, however this is
an emulation mode and issues arising while using this mode need to be recreated
under X11 before they will be addressed.

== Windows
=== wxWidgets 3.0.2

Mirror printing can be broken because of a bug in wxWidgets version 3.0.2,
see link:https://bugs.launchpad.net/kicad/+bug/1463406[Bug# 1463406].

=== Boost 1.59
On 64-bit Windows, KiCad's usage of the boost context library is currently broken
due to changes in the library. This causes pcbnew to crash on start.
The only workaround is to use boost 1.56 or 1.57 which are known to work.

== macOS
