+++
title = "Report a Bug"
[menu.main]
    parent = "Help"
    name   = "Report a Bug"
weight = 35
+++
:toc: macro 
:toc-title:

toc::[]

If you think you found a bug, what information should you include in my bug report to give as much helpful information to developers as possible?

Before you get too involved, you should first head over to the https://bugs.launchpad.net/KiCad/+bugs?orderby=-date_last_updated&start=0[KiCad bug tracker]
and check to see if a bug report for the problem you're seeing hasn't already been reported.

Filing high quality bug reports is important to help the KiCad developers fix bugs and improve the quality of KiCad. Good bug reports allow developers to
quickly find and resolve bugs which save limited developer time. Bug reports should only contain one issue. The Launchpad bug status reporting 
only allows for a single status condition per bug report. Submitting a good bug report requires you to do some information gathering before submitting your bug.

== Content of a bug report
In which KiCad application did the problem occur? KiCad is made up of several individual programs. If you are not sure which program you are using, open the about dialog. 
The application name is in the title bar of the about dialog.

Which version of KiCad are you using? This is critical. There is nothing worse wasting developers time looking for a bug that has already been fixed only to find out that 
the version of KiCad you are using is two stable releases old. The build information can be found in the About dialog. Please include the full version information, for example "(2013-07-07 BZR 4402)-stable".

What platform is KiCad being run on? The operating system and version information, for example Ubuntu 14.4, Debian Squeeze, Windows 7, OSX, etc.

What version of wxWidgets was used to build KiCad. You can find this information in the Help -> Copy Version Info menu. Please include the full description, for example wxWidgets 3.0.2.

If you are building KiCad from source, it is often helpful to know which tools you are using. Some examples are GCC 4.4.2, Visual Studio 2005, GCC 3.4.5 on MinGW, CMake 2.6.3, etc. 
Also including any custom compiler, linker, and CMake options may be helpful.

As of BZR version 2457 of the testing branch, the KiCad developers have provided an easier solution for gathering the required information. 
If the application you wish to file a bug report against is running, you can copy most if not all of the above information to the clipboard by selecting the "Copy Version Information" 
entry in the "Help" menu and pasting it into your bug report. Even if the application doesn't run, you can use one of the other KiCad applications to get the build
 and platform information and manually edit the application name.

If you can reliably repeat the problem, please include the exact steps that cause it. Explain it step by step, such that there is no guessing what steps you performed. 
If the problem occurs with a specific file or library, please attach it to your bug report if possible.

Now with all your information in hand head on over the the https://bugs.launchpad.net/KiCad/+bugs?orderby=-date_last_updated&start=0[KiCad bug tacker].

The KiCad developer team thanks you for your efforts.

== Auxiliary help with launchpad

You can track the status of your bug by following the instructions at https://help.launchpad.net/Bugs/Subscriptions

For a summary of fields in a bug report and the meanings of their allowed values: http://blog.launchpad.net/general/of-bugs-and-statuses