+++
title = "System Requirements"
aliases = [ "/post/system-requirements/" ]
[menu.main]
    parent = "Help"
    name   = "System Requirements"
weight = 50
+++
:toc: macro 
:toc-title:

toc::[]

== Common System Requirements (hardware specs):

- Pentium-compatible PC (Pentium IV, Athlon or more-recent system recommended);

- 512 MB RAM (1024 MB RAM recommended);

- Up to 5GB available hard disk space;

- 1280x1024 resolution (higher resolution recommended), with at least 16K colors.

- Graphic card with at least OpenGL 2.1, with hardware shaders. Check
  the opengl specs of the card:
  - Intel: No cards that came before the HD-Graphics, regardless of the wording HD.
    Intel cards that are reported working starts from model HD2000 and higher.
  - NVidia: from NVIDIA support page: http://www.nvidia.com/object/nv_ogl2_support.html
    NVIDIA support for OpenGL 2.0 begins with the Release 75 series of drivers.
    GeForce FX (NV3x), GeForce 6 Series (NV4x), NV3xGL-based Quadro FX and NV4xGL-based
    Quadro FX GPUs, and all future NVIDIA GPUs support OpenGL 2.0.
  - Ati: should work any modern Radeon chip even in the APU (GPU in the main processor),
    but check for some issues here:
    http://kicad-pcb.org/help/known-system-related-issues/#_bad_graphics_cards

== Common System Requirements (software specs):

- See: http://kicad-pcb.org/help/known-system-related-issues/ for
  software specific issues.

== Specific System Requirements

=== Windows

The software and hardware prerequisites for installing KiCad on a Windows
system are as follows:

Microsoft Windows XP SP3, Vista, Windows Server 2008, Windows 7,
Windows 8, Windows Server 2012, or Windows 10;

=== Apple - Mac OS X

The software and hardware prerequisites for installing on a Apple Mac OS
X computer are as follows:

Mac OS X 10.7 (Lion) or higher;

=== GNU/Linux

The software and hardware prerequisites for installing on Linux are as
follows:

Any modern Linux distro with OpenGl 2.0 or higher enabled
graphics should go. For example Linux Ubuntu 12.04 or higher.

=== Android/Linux

The Android/Linux platform is actually NOT supported.

=== Other OSes

Other systems (notably Unix *BSD) may be fully working but are actually
not officially supported.


