+++
title = "System Requirements"
aliases = [ "/post/system-requirements/" ]
[menu.main]
    parent = "Help"
    name   = "System Requirements"
weight = 50
+++
:toc: macro 
:toc-title:

toc::[]

== Common System Requirements (hardware specs)

* Pentium-compatible PC (Pentium IV, Athlon or more-recent system recommended);

* 512 MB RAM (1024 MB RAM recommended);

* Up to 5GB available hard disk space;

* Screen resolution of 1024x768 works but, 1280x1024 or higher is recommended,
  with at least 16K colors (with 1024x768 some buttons may result hidden but
  corresponding commands should be reachable via menu anyway).

* Graphic card with at least OpenGL 2.1, with hardware shaders. Check
  the OpenGL specs of the card:
** Intel: no cards that came before the HD-Graphics series, regardless of the name including "HD".
   Intel cards that are reported working starts from model HD2000 and higher.
** NVIDIA: from NVIDIA support page: http://www.nvidia.com/object/nv_ogl2_support.html
   NVIDIA support for OpenGL 2.0 begins with the Release 75 series of drivers.
   GeForce FX (NV3x), GeForce 6 Series (NV4x), NV3xGL-based Quadro FX and NV4xGL-based
   Quadro FX GPUs, and all future NVIDIA GPUs support OpenGL 2.0.
** AMD/ATI: should work any modern Radeon GPU, but check for some issues here:
   http://kicad-pcb.org/help/known-system-related-issues/#_bad_graphics_cards

== Common System Requirements (software specs)

See: http://kicad-pcb.org/help/known-system-related-issues/ for software specific issues.

== Specific System Requirements

=== Windows

The software and hardware prerequisites for installing KiCad on a Windows
system are as follows:

Vista, Windows Server 2008, Windows 7, Windows 8, Windows Server 2012, or Windows 10;

=== Apple - Mac OS X

The software and hardware prerequisites for installing on a Apple Mac OS
X computer are as follows:

Mac OS X 10.7 (Lion) or higher;

=== GNU/Linux

The software and hardware prerequisites for installing on Linux are as
follows:

Any modern Linux distro with OpenGl 2.0 or higher support should work fine. For example Ubuntu 14.04 or higher.

=== Other OSes

Other systems (notably Unix *BSD) may be fully functional but are not officially supported.
