+++
title = "System Requirements"
aliases = [ "/post/system-requirements/" ]
[menu.main]
    parent = "Help"
    name   = "System Requirements"
    weight = 50
+++
:toc: macro
:toc-title:

toc::[]

== Common System Requirements (hardware specs)

* Supported Processor Architectures
** Intel (or compatible) 32 and 64 bit.
** PowerPC 32 and 64 bit.
** ARM 32 and 64 bit.
** MIPS 64 bit.

* 1GB RAM (2G RAM recommended);

* Up to 10GB available hard disk space;

* Screen resolution of 1280x1024 works but 1920x1080 or higher is recommended, with at
  least 16K colors.  At lower resolutions toolbar buttons may be hidden but corresponding
  commands should be reachable via menu.

* Graphics card with OpenGL 2.1 or greater that supports hardware shaders. Check
  the OpenGL specs of the card:
** Intel: no cards that came before the HD-Graphics series, regardless of the name including "HD".
   Intel cards that are reported working starts from model HD2000 and higher.
** NVIDIA: from NVIDIA support page: http://www.nvidia.com/object/nv_ogl2_support.html
   NVIDIA support for OpenGL 2.0 begins with the Release 75 series of drivers.
   GeForce FX (NV3x), GeForce 6 Series (NV4x), NV3xGL-based Quadro FX and NV4xGL-based
   Quadro FX GPUs, and all future NVIDIA GPUs support OpenGL 2.0.
** AMD/ATI: should work any modern Radeon GPU, but check for some issues here:
   http://kicad-pcb.org/help/known-system-related-issues/#_bad_graphics_cards

== Common System Requirements (software specs)

See: http://kicad-pcb.org/help/known-system-related-issues/ for software specific issues.

== Specific System Requirements

KiCad supports major operating systems that remain supported by their developers.  After the
operating systems' respective organizations stop releasing updates for the system, KiCad will
not be specifically tested with the unsupported system.  Unsupported operating systems may
continue to work with KiCad beyond this time but bugs must be reproduced on a supported operating
system before they will be addressed by KiCad.

=== Windows

The software prerequisites for installing KiCad on a Windows system are as follows:

[%header,width="75%",cols="^2,4"]
|===
|Operating System       | Support Status
|Windows 7              | Unsupported, will most likely still function
|Windows 8              | Unsupported, will most likely still function
|Windows 8.1            | 10-Jan-2023
|Windows Server 2012    | 10-Oct-2023
|Windows Server 2016    | 10-Oct-2027
|Windows Server 2019    | 09-Jan-2029
|Windows 10             | 09-Jan-2029
|===

[%hardbreaks]
=== Apple - macOS

The software prerequisites for installing on a macOS system are as follows:

[%header,width="50%",cols="10,^2"]
|===
|Operating System | End of Support:
|macOS 10.12      | Unsupported
|macOS 10.13      | 1-Aug-2020
|macOS 10.14      | 1-Aug-2021
|===

[%hardbreaks]
=== GNU/Linux

The following Linux distributions have been tested and are known to be working with
KiCad version 5.1.
Issues or bugs that occur on an unsupported platform must be reproduced on an officially
supported distribution and window manager before they will be addressed by KiCad.

*Note:* Development versions of the next KiCad release (version 6) may not function
on some of the older distributions listed below.


==== Ubuntu

[%header,width="75%",cols="^2,4"]
|===
|Operating System       |End of Support:
|Ubuntu 16.04 (LTS)     |Unsupported, will most likely still function
|Ubuntu 18.04 (LTS)     |1-Apr-2021
|Ubuntu 18.10           |Unsupported, will most likely still function
|Ubuntu 19.04           |Unsupported, will most likely still function
|Ubuntu 19.10           |1-July-2020
|===

Long Term Support (LTS) releases of Ubuntu will be supported for 1 year after the next
LTS version is released (for a total of 3 years of support).

Non-LTS releases of Ubuntu will be supported while the version
is under https://wiki.ubuntu.com/Releases[standard support] from Ubuntu.


==== Fedora

[%header,width="75%",cols="^2,4"]
|===
|Operating System       |End of Support:
|Fedora 29              |Unsupported, will most likely still function
|Fedora 30              |approx May 2020
|Fedora 31              |approx November 2020
|===

Fedora releases will be supported for as long as they are supported by the Fedora Project
(usually for 1 year after release).


==== Debian

[%header,width="75%",cols="^2,4"]
|===
|Operating System       |End of Support:
|Debian 9 (Stretch)     |approx 2020
|Debian 10 (Buster)     |approx 2022
|===

Debian releases will be supported for as long as they are https://wiki.debian.org/DebianReleases#Production_Releases[supported]
by Debian.


[%hardbreaks]
==== Additional Linux Considerations
Linux allows users to select their preferred window manager.  There are many esoteric window
managers available for Linux and some may have unexpected behavior.  KiCad officially supports
the following window managers:

* Metacity (used by GNOME 2 and GNOME flashback)
* Mutter (GNOME 3)
* KWin (KDE)
* Xfwm (used by XFCE)
* i3 (Arch Linux)
* Unity (Ubuntu prior to 18.04)

==== Graphical Windowing Backend
Regardless of the window manager, KiCad officially only supports the X11 backend.  Users who
choose to use Wayland will have to run KiCad in the compatibility layer
link:https://wayland.freedesktop.org/xserver.html[XWayland].

Issues or bugs encountered while using XWayland must be reproduced under X11 before they
will be addressed by KiCad.  Bugs that cannot be reproduced on X11 should be reported to
the link:https://gitlab.freedesktop.org/wayland/wayland/issues[Wayland bug tracker].


=== Other OSes

Other systems (notably Unix *BSD) may be fully functional but are not officially supported.
