+++
title = "Upgrading"
aliases = [
    "/help/migration/"
]
[menu.main]
    parent = "Help"
    name   = "Upgrading"
    weight = 40
+++

Newer versions of KiCad bring changes to file formats and functionality. While effort is made to maintain compatibility, there may ultimately be changes that must made
in existing projects to adapt to the changes.

== Upgrade from 4.0 to 5.0
Information on upgrading from 4.0 to 5.0 can be found in the 
http://docs.kicad-pcb.org/5.0.2/en/kicad/kicad.html#upgrading_from_version_4_to_version_5[KiCad help manual].


== Upgrade from any version before 4.0 (also known as "old-stable")

=== Issues are fixed in 5.1.1

Note that the issues referenced below are resolved by the upcoming KiCad version 5.1.1.  Layer names will be translated to the standard English names on opening and will be written out as English when the file is saved.

=== Layernames are translated

There is a known issue when migrating designs from the old stable, revision around bzr revision 4022, where layer names were translated, which they should never have been.  This issue arises if you used KiCad localized for Italian, French or Polish.

To resolve this issue, you will to edit all `.kicad_pcb` files with a text editor (notepad, ...) and change the layer names from Italian/French/Polish to their English counterparts. Below is the correspondance of the layer names. Caution: there are more instances to replace than just the layer list. Be sure that you don't miss any.

==== New English names
----
(layers
  (32 B.Adhes user)
  (33 F.Adhes user)
  (34 B.Paste user)
  (35 F.Paste user)
  (36 B.SilkS user)
  (37 F.SilkS user)
  (38 B.Mask user)
  (39 F.Mask user)
  (40 Dwgs.User user)
  (41 Cmts.User user)
  (42 Eco1.User user)
  (43 Eco2.User user)
  (44 Edge.Cuts user)
)
----

==== Obsolete Italian names
----
(layers
  (16 Adesivo.Retro user)
  (17 Adesivo.Fronte user)
  (18 Pasta.Retro user)
  (19 Pasta.Fronte user)
  (20 Serigrafia.Retro user)
  (21 Serigrafia.Fronte user)
  (22 Maschera.Retro user)
  (23 Maschera.Fronte user)
  (24 Grafica user)
  (25 Commenti user)
  (26 Eco1 user)
  (27 Eco2 user)
  (28 Contorno.scheda user)
)
----

==== Obsolete French names
----
(layers
  (16 Dessous.Adhes user)
  (17 Dessus.Adhes user)
  (18 Dessous.Pate user)
  (19 Dessus.Pate user)
  (20 Dessous.SilkS user)
  (21 Dessus.SilkS user)
  (22 Dessous.Masque user)
  (23 Dessus.Masque user)
  (24 Dessin.User user)
  (25 Cmts.User user)
  (26 Eco1.User user)
  (27 Eco2.User user)
  (28 Contours.Ci user)
)
----

==== Obsolete Polish names
----
(layers
  (16 Kleju_Dolna user)
  (17 Kleju_Gorna user)
  (18 Pasty_Dolna user)
  (19 Pasty_Gorna user)
  (20 Opisowa_Dolna user)
  (21 Opisowa_Gorna user)
  (22 Maski_Dolna user)
  (23 Maski_Gorna user)
  (24 Rysunkowa user)
  (25 Komentarzy user)
  (26 ECO1 user)
  (27 ECO2 user)
  (28 Krawedziowa user)
)
----

=== Schematic libraries are updated

Be aware that the schematic libries has gotten an overhaul (still in
progress), which means that it will easily break your schematics,
because the bundled libs takes precedence over the cache lib. What you
can do to recover is to remove the libs used in the project and rename
the cache lib file, and include that instead. Chris Pavlina has
recently made a wizard to help with this issue, this has been merged
in the product branch now.

