+++
brief = "Naming conventions for connector footprints."
layout = 'single_fp_name'
title = 'Connectors'
+++

Footprint naming is sufficiently complex that a link:/klc/F2.1/[general rule] is not enough to fully define the wide range of footprints.

Following is a list of naming conventions for various groups of footprint types. If you do not find a matching convention in the list below, contact the KiCad library team or find an existing set of components in the libraries that closely match your requirements.

{{< fp_naming_common >}}

=== Connectors
```
{[generic series name]_}{[manufacturer specific identification]}{_[pin configuration]_P[pin pitch]}{_Pad[pad length]{x[pad width]}}_[orientation]{_footprint options}
```
The pin configuration field is dependent on the connector type.

* Single row connectors: 1x[number of pins]
* Multi row connectors with equal number of pins in each row: [number of rows]x[number of pins per row]
* Other connectors: [number of rows]Rows_[number of pins]
* Connectors for standardized interfaces do not need to include the pin configuration information. (Example USB)

Number format:

* [number of rows] number of rows no leading zero.
* [number of pins per row] and [number of pins] two digit number with leading zero. (can have more digits for connectors with > 100 pins)

generic series name: The generic name for the type of connector.

The orientation of connectors is determined by the plug direction.

{{< klcimg_full_width src="connector_orientation" title="The orientation of connectors is determined by the plug direction." >}}

==== Manufacturer specific connectors (JST_EH, Molex_PicoBlade, ...)
```
[MAN]{_[manufacturer series name]}_[MPN]_[pin configuration]_P[pin pitch]{_Pad[pad length]{x[pad width]}}_[orientation]{_footprint options}
```

==== Connectors for standardized interfaces with manufacturer specific footprints (USB, HDMI, SD-Card, ...)
```
[generic series name]_[MAN]{_[manufacturer series name]}_[MPN]{_Pad[pad length]{x[pad width]}}_[orientation]{_footprint options}
```

generic series name:

i. `USB{_[Standard]}{_[Size]}_[Type]`
  * Standard only needed for USB 3 (non backward compatible connectors)
  * Size: none, micro, mini
  * Type: A, B, C
i. `HDMI_[Type]`
  * Type A = Normal, Type B = Dual Link, Type C = Mini, Type D = Micro, Type E = Automotive
i. `DVI_[Type]{_Size}`
  * Type: I = integrated, D = digital only, A = analog only
  * Size: None = normal, Mini or Mircro
i. `SD_[Standard]{_[Size]}{_UHS_[UHS Type]}`
  * Standard: SC, HC, XC or IO (Specification of your component. Yes some of them are Backwards compatible, give the highest standard specified.)
  * Size: None = normal, Mini, Micro
  * For UHS enabled components the UHS type needs to be given.

==== Connectors for standardized connectors with manufacturer specific footprints (DSUB, Tab, ...)
```
[generic series name]_[MAN]{_[manufacturer series name]}_[MPN]_[pin configuration]_P[pin pitch]{_Pad[pad length]{x[pad width]}}_[orientation]{_footprint options}
```
The main difference between thes type of connectors and standardized interface connectors is the inclusion of the pin configuration.

==== Generic connector footprints (For standardized connectors like: Pin headers, socket strips, ...)
```
[generic series name]_[pin configuration]x[pin pitch]mm{_Pad[pad length]{x[pad width]}}_[orientation]{_footprint options}
```
Generic connectors do not include manufacturer specific information.

==== Terminal Blocks (Screw headers)
```
TerminalBlock_[MAN]{_[manufacturer series name]}_[MPN]_[pin configuration]x[pin pitch]mm{_Pad[pad length]{x[pad width]}}_[orientation]{_footprint options}
```
Orientation:
For terminal Blocks the orientation is determined by the direction of the cable slot.

{{< klcimg_full_width src="terminal_block_orientation" title="For terminal Blocks the orientation is determined by the direction of the cable slot." >}}
