+++
brief = "Naming conventions for capacitor footprints."
layout = 'single_fp_name'
title = 'Capacitor'
+++

{{< fp_naming_common >}}

For each of the items listed below, if the footprint is specific to a single manufacturer, then the footprint name should be prefixed as follows:

`[MAN]\_[MPN]_` (More detailse see link:/klc/F2.4/[F2.4 Manufacturer Specific Footprints])

=== Capacitor Footprints
```
[C | CP]{_[style]}{_[Body Size]_P[pitch]}{_Pad[pad modifier]}}{_footprint options}
```

* C for non polarized capacitors
* CP for polarized capacitors

There are different capacitor styles available:

* Axial: Cylindrical body with axial lead attachment.
* Radial: Cylindrical body, both leads enter at same end.
** This type of capacitor can be THT or SMD.
* Disc: Disc shaped body (sometimes enclosed), leads enter tangent to the inner disc
* Rect: Box shaped body

Body Size:

* For Axial body styles: L[lenght]_D[diameter]
* For Radial body style: D[diameter]{_H[height]}
* For Disc body style: D[diameter]_W[width]
* For box shaped body styles: [X]x[Y]{x[Z]}

==== Standardized two terminal rectangular SMD packages (Ceramic capacitors)
```
C{{< fp_naming_TwoTerminal >}}
```
link:{{< relref "klc/F2.5/FP-Naming_TwoTerminalSMD.adoc" >}}[More details]

==== Standard THT capacitor
```
[C | CP]_[style]_[Body Size]_P[pitch]_{_Pad[pad modifier]}}{_footprint options}
```
