+++
title = "About KiCad"
date = "2014-04-09"
aliases = [ "/about/" ]
categories = [ "About" ]
[menu.main]
    parent = "About"
    name   = "KiCad"
+++

{{< aboutlink "/img/about/kicad-logo.png" "/img/kicad_logo_paths.svg" >}}

KiCad is an http://en.wikipedia.org/wiki/Open_source[open source] software suite for
http://en.wikipedia.org/wiki/Electronic_design_automation[Electronic Design Automation] (EDA).
The programs handle http://en.wikipedia.org/wiki/Schematic_capture[Schematic Capture],
and http://en.wikipedia.org/wiki/Printed_circuit_board[PCB] Layout with
http://en.wikipedia.org/wiki/Gerber_format[Gerber] output. The suite runs on Windows, Linux
and macOS and is licensed under http://en.wikipedia.org/wiki/GNU_General_Public_License[GNU GPL v3].

== History
The first release date was in 1992 by its original author, Jean-Pierre Charras,
but is now currently under development by the https://launchpad.net/kicad[KiCad Developers Team].

The name of KiCad comes from the first letters of a company of Jean-Pierre Charras' friend "Ki"
being combined with "Cad". But it now has no meaning other than being the name of the software
suite. https://lists.launchpad.net/kicad-developers/msg27528.html[Mentioned by Jean-Pierre in an email.]

More KiCad history, general information, and advancements can be found in Wayne's
https://www.youtube.com/watch?v=wRolB1my6fI[2015],
https://www.youtube.com/watch?v=yNe6g0OdGs4[2016],
https://www.youtube.com/watch?v=SlxpHWB_vb8[2017],
https://www.youtube.com/watch?v=wWpeDpDTvUU&t=14s[2018], and
https://www.youtube.com/watch?v=qsjU7Rcs3vA&t=7s[2019]
FOSDEM presentations.


== Main Authors

[options="header"]
|===
|Name | Email
|Jean-Pierre Charras | jp.charras[at]wanadoo-dot-fr
|Dick Hollenbeck | dick[at]softplc-dot-com
|Wayne Stambaugh (Project Leader) | stambaughw[at]gmail-dot-com
|===


== Corporate Supporters

{{< aboutlink "/img/about/gipsa-logo.png" "http://www.gipsa-lab.grenoble-inp.fr/" >}}

=== University of Grenoble and GIPSA-lab

This is the university where Jean-Pierre Charras, the original author of KiCad, worked as a
teacher before his retirement.  They provided hosting for the releases of KiCad, giving us a
large amount of bandwidth for the large downloads.

Jean-Pierre has also been able to invest large amounts of time into developing KiCad.

{{< aboutlink "/img/about/softplc-logo.png" "http://www.softplc.com/" >}}

=== SoftPLC

SoftPLC, Dick Hollenbeck's employer, sponsored him to improve KiCad's
functionality immensely which resulted in an extremely intesive and prolific
era for KiCad in which Dick committed an extremely generous amount of work.

SoftPLC sponsored Dick to the equivalent of 450,000USD for the time he spent working on KiCad.

{{< aboutlink "/img/about/cern-logo.png" "http://home.web.cern.ch/" >}}

=== CERN

Employer of Javier Serrano, Maciej Suminski and Tomasz Wlostowski who all work heavily on KiCad.

CERN has already contributed greatly to KiCad, and have already advanced the Graphics
Abstraction Layer and introduced Push and Shove router capabilities.

{{< aboutlink "/img/about/rpi-logo.png" "https://www.raspberrypi.org/" >}}

=== The Raspberry Pi Foundation

Donated to the https://cernandsocietyfoundation.cern/projects/kicad[CERN and Society Foundation] for the development
of KiCad's differential pair routing and track length control features.

{{< aboutlink "/img/about/arduino-logo.png" "http://www.arduino.cc" >}}

=== Arduino LLC

Donated to the https://cernandsocietyfoundation.cern/projects/kicad[CERN and Society Foundation] to support CERN's
efforts in Open Source Hardware.

{{< aboutlink "/img/about/glesys.png" "http://glesys.se" >}}

=== GleSYS

Hosting provider for some of the servers used on the Jenkins CI.

{{< aboutlink "/img/about/digikey-logo.png" "http://www.digikey.com" >}}

=== Digi-Key Electronics

Digi-Key Electronics purchased the kicad.org domain name, which was being used by its previous
owner to serve malware, and redirected it to the main KiCad website at kicad-pcb.org.

{{< aboutlink "/img/about/aisler-logo.png" "https://aisler.net/partners/kicad" >}}

=== AISLER

AISLER believes that a PCB Design Tool like KiCad should participate financially when a
customer let’s that design become a reality.  That is why AISLER allows its users to easily
donate to the KiCad project during the ordering process.

{{< aboutlink "/img/about/tech-explorations-logo.png" "https://techexplorations.com/" >}}

=== Tech Explorations

https://techexplorations.com[Tech Explorations] is a technology education company for
Makers, STEM educators, and students.  Peter Dalmaris, the company co-founder recently
wrote and published
https://techexplorations.com/product/kicad-like-a-pro-2nd-edition-special-kicad-fundraising-edition-ebook-bundle/[“KiCad Like a Pro, 2nd edition”] which donates 50% of the book sale
profits to the KiCad project.

{{< aboutlink "/img/about/nextpcb-logo.png" "https://www.nextpcb.com/" >}}

== NextPCB

https://www.nextpcb.com/[NextPCB] has donated to KiCad and is dedicated to one stop solutions
for https://www.nextpcb.com/[PCB prototyping], small batch and mass production, selling and
sourcing of electronic components, SMT and
https://www.nextpcb.com/pcb-assembly-services[PCB assembly].

{{< aboutlink "/img/about/system76-logo.png" "https://system76.com/" >}}

== System76

https://system76.com/[System76] manufactures powerful Linux laptops, desktops, and servers
for the creators, builders, and innovators of tomorrow.  Because our computers are powered
by open source software, customers instantly have access to a plethora of free software and
tools.  We're proud to support KiCad's open source project, via our financial support through
the CERN and Society Foundation.
