+++
title = "About KiCad"
date = "2014-04-09"
aliases = [ "/about/" ]
categories = [ "About" ]
[menu.main]
    parent = "About"
    name   = "KiCad"
+++

{{< aboutlink "/img/about/kicad-logo.png" "/img/kicad_logo_paths.svg" >}}

KiCad is an http://en.wikipedia.org/wiki/Open_source[open source] software suite for
http://en.wikipedia.org/wiki/Electronic_design_automation[Electronic Design Automation] (EDA).
The programs handle http://en.wikipedia.org/wiki/Schematic_capture[Schematic Capture],
and http://en.wikipedia.org/wiki/Printed_circuit_board[PCB] Layout with
http://en.wikipedia.org/wiki/Gerber_format[Gerber] output. The suite runs on Windows, Linux and OS X
and is licensed under http://en.wikipedia.org/wiki/GNU_General_Public_License[GNU GPL v3].

== History
The first release date was in 1992 by its original author, Jean-Pierre Charras,
but is now currently under development by the https://launchpad.net/kicad[KiCad Developers Team].

The name of KiCad comes from the first letters of a company of Jean-Pierre Charras' friend "Ki" being combined with "Cad". But it has no other meaning other now being the name of the software suite. https://lists.launchpad.net/kicad-developers/msg27528.html[Mentioned by Jean-Pierre in an email.]

More KiCad history, general information, and advancements can be found in Wayne's 
https://www.youtube.com/watch?v=wRolB1my6fI[2015], https://www.youtube.com/watch?v=yNe6g0OdGs4[2016], and https://www.youtube.com/watch?v=SlxpHWB_vb8[2017] FOSDEM presentations.


== Main Authors

[options="header"]
|===
|Name | Email
|Jean-Pierre Charras | jean-pierre.charras[at]gipsa-lab-dot-inpg-dot-fr
|Dick Hollenbeck | dick[at]softplc-dot-com
|Wayne Stambaugh (Project Leader) | stambaughw[at]gmail-dot-com
|===


== Corporate Supporters

{{< aboutlink "/img/about/gipsa-logo.png" "http://www.gipsa-lab.grenoble-inp.fr/" >}}

=== University of Grenoble and GIPSA-lab

This is the university where Jean-Pierre Charras, the original author of KiCad, worked as a
teacher before his retirement.  They provided hosting for the releases of KiCad, giving us a
large amount of bandwidth for the large downloads.

Jean-Pierre has also been able to invest large amounts of time into developing KiCad.

{{< aboutlink "/img/about/softplc-logo.png" "http://www.softplc.com/" >}}

=== SoftPLC

SoftPLC, Dick Hollenbeck's employer, sponsored him to improve KiCad's
functionality immensely which resulted in an extremely intesive and prolific
era for KiCad in which Dick committed an extremely generous amount of work.

SoftPLC sponsored Dick to the equivalent of 450,000USD for the time he spent working on KiCad.

{{< aboutlink "/img/about/cern-logo.png" "http://home.web.cern.ch/" >}}

=== CERN

Employer of Javier Serrano, Maciej Suminski and Tomasz Wlostowski who all work heavily on KiCad.

CERN has already contributed greatly to KiCad, and have already advanced the Graphics
Abstraction Layer and introduced Push and Shove router capabilities.

{{< aboutlink "/img/about/rpi-logo.png" "https://www.raspberrypi.org/" >}}

=== The Raspberry Pi Foundation

Donated to the https://giving.web.cern.ch[CERN and Society Foundation] for the development
of KiCad's differential pair routing and track length control features.

{{< aboutlink "/img/about/arduino-logo.png" "http://www.arduino.cc" >}}

=== Arduino LLC

Donated to the https://giving.web.cern.ch[CERN and Society Foundation] to support CERN's
efforts in Open Source Hardware.

{{< aboutlink "/img/about/glesys.png" "http://glesys.se" >}}

=== GleSYS

Hosting provider for some of the servers used on the Jenkins CI.

{{< aboutlink "/img/about/digikey-logo.png" "http://www.digikey.com" >}}

=== Digi-Key Electronics

Digi-Key Electronics purchased the kicad.org domain name, which was being used by its previous
owner to serve malware, and redirected it to the main KiCad website at kicad-pcb.org.
