+++
title = "KiCad Licenses"
categories = [ "About" ]
[menu.main]
    parent = "About"
    name   = "Licenses"
+++
:toc: macro 
:toc-title:
:toclevels: 5

toc::[]

== Program License

KiCad is free software. KiCad is made available under the GNU General Public License(GPL) version 3 or greater.

There is no requirement to assign your copyright to anyone to get code included into KiCad. The only thing we do require is complying with the GPLv3+ license both in the code you may write and code you may import from others.

== Documentation License

link:/help/documentation/[KiCad documentation] is distributed under a two license choice of either the GNU General Public License version 3 or later, or the Creative Commons Attribution License version 3.0 or later.

== Website License

Unless otherwise stated, all text and images on this website are licensed under either a choice of the Creative Commons Attributions License, version 3.0 or later; or the General Public License version 3 or later. This does not include the KiCad source code, libraries, documentation, and any third party tools or products mentioned on the website.

== Terms
include::/content/about/licenses/gplv3.adoc[]
include::/content/about/licenses/cc-by-3.0.adoc[]
