+++
title = "Getting Started"
[menu.main]
    parent = "Discover"
    name   = "Getting Started"
+++

== Getting started

This is a simple guide to get you started using KiCad. +
For more in-detail description on use, see the
link:http://docs.kicad-pcb.org/[documentation] and
link:http://tutorials.html[Tutorials] section.

=== Libraries

KiCad uses two separate libraries, symbols and footprints. +
Symbols is used when you draw your schematic, and then you 
assign the footprint to the symbol.

This means that there is several possible footprints
for a symbol, like a resistor can be of different sizes
and shapes, or like you can have a IC or transistor 
in several different packages.

==== Symbols

The schematic symbols is stored in the project file (`.pro`),
and when creating a new project the the tmplate project is
copied to the new project. 

To change the default schematics libraries open this 
project file and change the libraries there, this will
then be used on all _new_ projects.

==== Footprints

The footprints is stored in the 'footprint library
file', this file is modified from 'pcbnew'.

It is recomended to use the 'Add Footprint Library Wizard' to
download the footprint files from GitHub to be
able to use the footprints without downloading
from GitHub each time.

== Workflow

The basic workflow in KiCad is:

1. Create project.
2. Create a schematic with eeschema.
3. Assign footprints and generate the netlist.
4. Create the board, importing the netlist.
5. Generate production files.

WARNING: It is strongly recommended to use the same
name for both project file and its directory.

It's possible to open both schematic and PCB files
outside of the project manager (`kicad.exe`), but this
might result in unexpected results since the project
manager sets up the working environment for the other
tools.

TIP: If you need to transfer the project, use the
archive option in the file menu. +
All files needed to open the project will be added
to the archive.
