+++
title = "Known System Related Issues"
date = "2015-06-11"
+++

This page is just a small note on some "weird" issues that has been
experienced with KiCad in relation to the systems that it run on. This
means that this page should not describe KiCad functional bugs.

== Legacy Canvas and Wxgtk

The legacy canvas has problems with wxwidgets 3.0 built with gtk3,
this combination is usually called wxgtk on various package
distributions. Don't be confused when you see wxgtk 3.0.0 in your
package manager, this is usually referring to the wxwidgets version,
and not whether or not it is built against gtk3.

It has been seen that fedora 20, 21 and 22, builds against gtk3 and
you will experience the symptoms described below.

The symptoms, is that eeschema zooming will be slow, and the graphics
is not quite exact, try looking at the grid dots. And in pcbnew, the
canvas does not really draw near properly at all.

== Radeon Graphics

Some users with Radeon graphics has been experiencing problems with
slow rendering in gerbview and eeschema.
https://bugs.launchpad.net/kicad/+bug/1003859[Some]
https://bugs.launchpad.net/kicad/+bug/1186813[bugs] has been reported
on it, and the solution seemed to be change an Xorg setting. You have
to set `Option "EXAPixmaps" "off"`.

== Bad Graphics Cards

There is a few older cards that seem to no be have properly with the
OpenGL canvas used in the new GAL canvas. The list below has been
identified as such:

- Intel Graphics Media Accelerator (GMA) 4500M / Windows 7 64bit / crash
on startup (https://bugs.launchpad.net/kicad/+bug/1473786)
- ATI Hawaii XT [Radeon R9 290X] + 4K display + fglrx driver / Ubuntu
14.04 LTS / flashes when the rendering area is too big
(https://bugs.launchpad.net/kicad/+bug/1492117)
- ATI RV370 [Radeon X300 SE] + radeon driver / Xubuntu 14.04.1 / does
not display line rounded line ends
(https://bugs.launchpad.net/kicad/+bug/1498970)

== Boost 1.54

There has previously been problems with internal bugs in boost,
whereby at one point in time the developers decided to include
download, patch and build of boost in the KiCad build framework. Many
users have been reluctant to understand this fact. Once a build option
to skip this download and build was added, such that you can save some
initial build time and actually use the boost you already have
installed on your system.

This downloading depends inside the KiCad installer framework is being
slowly removed again, because it has been acknowledged that is is a
bad idea, because it clutters the KiCad installer. Instead such things
should be an external project. If you have boost 1.56+ this skipping
seems fairly safe now a days. Use the option `-DKICAD_SKIP_BOOST=ON`
when cmake'ing.

== WxGTK 3.0.1

Version 3.0.1 of wxwidgets for linux (with gtk) can crash when running
DRC. This is an issue not seen in WxGTK 3.0.2, so it seems to be fixed
upstream. More details can be found in
link:https://bugs.launchpad.net/kicad/+bug/1442909[Bug# 1442909].
Wxwidgets 3.0.2 on windows

Mirror printing can be broken because of a bug in the wxwidgets
version 3.0.2, see link:https://bugs.launchpad.net/kicad/+bug/1463406[Bug# 1463406].

== Retina display slow

On OS X machines with the new retina display (aka. HiDPI display) you
might have trouble with rendering lag because of the high resolution.
The rendering speed can be improved by adjusting the KiCad.app startup
options to force low resolution. You can do that by setting the "Open
in Low Resolution" checkbox in the app "Get Info" dialog. For a step
by step description refer to the "*I'm noticing functional or visual
issues with an application. How can I make it work better?*" section in
the https://support.apple.com/en-is/HT202471[OS X support article].

