+++
title = "Building KiCad on Windows"
+++

:icons: fonts
:iconsdir: /img/icons/

Instructions to build KiCad on Window can be found 
directly from the 
link:https://launchpad.net/kicad-winbuilder[Kicad Winbuilder]
or from the generic
link:https://launchpad.net/kicad[KiCad source tree].

Also an easy way is to use the
link:http://sourceforge.net/projects/msys2/[MSYS2]
environment, instructions below.

== Using MSYS2 to build on windows
****
1. Get link:https://msys2.github.io/[MSYS2]

2. Follow the link:http://sourceforge.net/p/msys2/wiki/MSYS2%20installation/[updating packages to update].That is you probably need to do:

   a. `pacman -Sy; pacman --needed -S bash pacman pacman-mirrors msys2-runtime`
   b. Restart the MSYS2 shell
   c. `pacman -Su`

3. `pacman -S base-devel git`

4. `pacman -S mingw-w64-x86_64-toolchain`

5. `cd ~; git clone https://github.com/Alexpux/MINGW-packages.git`

6. `cd ~/MINGW-packages/mingw-w64-kicad-git`

7. `makepkg-mingw -sLi`
****
The `-i` option is to install after build.
Repeat step 7 to update your installation. +
Also in step 4, you don't need to do install
the `x86_64` toolchain, you can also use the
`i686` toolchain if your system is not 64 bit.
Follow all the steps mentioned above, when this
is completed succesfully you can jump to the
next section.

== Developer way

This section asumes that you have set up your
MSYS2 environment as described in the steps
above. Using `makepkg-mingw` will build a
pacman package, but if you are trying to
develop on KiCad that is likely not what you
want. +
In that case you should use cmake and make
directly. +
You should open the respective MSYS2 shell for
the architecture that you want to build for and
then do:

 mkdir build; cd build
 cmake -G "MSYS Makefiles" -DKICAD_SKIP_BOOST=ON ..
 make

And if you actually did decide to do
developement, you might also want to add
`-DCMAKE_BUILD_TYPE=Debug` cmake option.
