+++
title = "Developers"
categories = [ "Contribute" ]
[menu.main]
    parent = "Contribute"
    name   = "Developers"
weight = 20
+++
:toc: macro 
:toc-title:

toc::[]

== Getting Started

link:https://launchpad.net/kicad[KiCad uses Launchpad]
for bug reporting and tracking, source code hosting, 
and creating blueprints (roadmaps) of new features. The project is 
essentially managed through Launchpad.
The first thing to do before anything is to join the 
link:https://launchpad.net/~kicad-developers[KiCad Developers Mailing List].
You can also join the link:/community/irc[IRC channel]
if you have questions. Usually, there are multiple KiCad developers in the channel.

To report bugs and help with technical subjects you
will need a Launchpad account. To commit source code,
you will additionally need to set up SSH keys for your
account. Detailed instructions for setting up an account
are available in the
link:https://help.launchpad.net/YourAccount/NewAccount[Launchpad user tutorial].

=== Fetching the Source Code

The first step is to obtain the source code.
You will need to get the latest sources in order
to develop KiCad.

KiCad uses the 
link:http://bazaar.canonical.com/en/[Bazaar]
version control system. Platform-specific installation 
instructions are available here. On Debian and related systems
(e.g. Ubuntu), you need to install the bzr package.
On Windows, you'll need to download and execute the installer.

We recommend to set up a Launchpad account (see above) before
obtaining the source code, since that way it is easier to
commit later once you get commit access. Once you set up your
Launchpad account, execute the following commands:
****
`bzr whoami "Real Name <email@address.com>"` +
`bzr launchpad-login username`
****
where `Real Name` is your real name or a pseudonym you want to
use (it should be recognizable to people on the developer mailing
list), `e-mail@domain.tld` is your e-mail for KiCad related
correspondence (it can be obfuscated if you want), and `username`
is you Launchpad user name. With this setup, you will be able to
commit once you are approved as a member of the KiCad Committers
team on Launchpad.

To obtain the latest source code, use the following command:
****
`bzr checkout lp:kicad`
****
To update this code later, you can use
****
`bzr update`
****
Alternatively there is a git mirror hosted on github:
****
`git clone https://github.com/KiCad/kicad-source-mirror.git`
****
=== Read the Code Style Policy

The first thing to do is to check the
link:http://ci.kicad-pcb.org/job/kicad-doxygen/ws/Documentation/doxygen/html/md_Documentation_development_coding-style-policy.html[Coding Style Policy] - it's
important for us to keep the codebase readable by all developers.
This generally gets philosophical, but the code base needs
consistency throughout, so please do pay attention to the code
style policy. Your patches will generally be rejected if they do not adhere
to the rules set forth in the policy.

=== Using Bazaar

As mentioned above, you firstly need to get a fresh copy of the
latest sources:
****
`bzr checkout lp:kicad`
****
Generally, this copy is kept clean, without modifications.
Using Bazaar it's possible to branch locally so that you can make
changes in a copy which are specific to the new feature your working
on, or the bug your trying to fix. To branch locally, you can use the
command:
****
`bzr branch ./kicad ./kicad-feature`
****
where `./kicad-feature` is where you want to start developing code.

Start developing code in `./kicad-feature` to add new functionality
or fix a bug. If you're fixing a bug that you've noticed yourself
and haven't seen a bug report for, please report it as a bug so that
others are aware of it being reported already and that you're working
on a fix!

Whilst developing in `./kicad-feature` you can commit as many times
as you like. This commits to `./kicad-feature` only and does not
commit to the main copy on launchpad. You should keep your changes
up-to-date with what everyone else is doing in case conflicts arise.
You can do this by keeping the original kicad folder up-to-date and
merging the differences in every-so-often with the following commands:
****
`cd ./kicad` +
`bzr update` +
`cd ../kicad-feature` +
`bzr merge ../kicad` +
`bzr commit -m "Merged in latest changes"`
****
Once you're finished developing the feature you should do the above
before generating a patch to send to the developers list.
To generate the patch, you can simply the following command from the
kicad-feature directory:
****
`bzr diff > feature.patch`
****
Attach feature.patch to an email and send it to the developers list.
Start the subject line with 'PATCH:' so that everyone is aware there
is a patch to review.

As an alternative to emailing a patch, you can push your branch for
review and a possible merge into the KiCad source code by using the
following commands when you've finished developing a feature:
****
`bzr push lp:~[your-launchpad-username]/kicad/[new-branch-name]`
****
=== Using Git

There are a lot of people using the Git version control system and
want to stay in their comfort-zone of using it instead of using Bazaar.
This is no problem, don't feel alienated just because of a vcs!
Git can be used with the git-bzr adaptor.

It is possible to hack on KiCad and use the git tools instead of bzr.
If you follow these instructions you can tailor your development to
be comfortable and efficient for your needs.

We use a tool called git-bzr-ng to allow git to talk to bzr remote
hosts. Our repositories are all bzr branches, but that shouldn't
matter to you at all. Your own branches on your computer can be git
and you can talk to our bzr branches as if they were on github or
other git host provider.

==== Installing git-bzr

If you are using a Debian/Ubuntu computer for your development needs,
you can simply install git-bzr-ng from the command line like so:
****
`sudo apt-get install git-bzr-ng`
****
If you're using Fedora, you can install git-bzr using yum:
****
`sudo yum install git-bzr`
****
For Windows, Mac and other Free Desktops/Linux systems, please see
the documentation link:https://github.com/pieter/git-bzr[here].

==== Using Git

Once you have the plugin above installed, you should be able to use
the git command with bzr repositories. To access KiCad, use the
following commands:
****
`git bzr clone lp:kicad kicad` +
`cd kicad`
****
Create a git branch and check your branches:
****
`git checkout -b touch_branch` +
`git branch -a`
****
Now you can follow whatever Git workflow you prefer.
In order to contribute you can simply generate a unified patch,
attach it to an email and send it to the KiCad Developers mailing list.
Make sure you start the subject line with 'PATCH:' so everyone is aware
there is a patch attached that requires review.
Please be patient with patch reviews - it can take some time to get
round to reviewing patches, especially if there's a flurry of them!

Alternatively, to commit and push your changes to a new kicad branch
ready for review, be aware that you *do need* a launchpad account with your 
link:https://help.launchpad.net/YourAccount/CreatingAnSSHKeyPair[ssh keys uploaded]
in order to push your changes:
****
`git commit -a -m "Commit message"` +
`git bzr push lp:~[your-launchpad-username]/kicad/[new_branch_name]`
****
For example `git bzr push lp:~brian-sidebotham/kicad/fix-for-bug466366`
will push to my very own branch which can be reviewed and merged.

To merge in someone else's changes (a merge in bzr terms) you can use
these commands:
****
`git bzr import lp:~user/kicad/branchname branchname` +
`git checkout kicad` +
`git pull . -- branchname`
****
Further reading on
link:http://bazaar.launchpad.net/%7Etermie/git-bzr-ng/master/view/head:/README.rst[git-bzr usage].

== How to Contribute

After you have setup your development machine by fetching the source and making sure that you can build as described above, you might or might not know what to actually contribute. If the latter, this is the page for you.

There are multiple ways of contributing to the future success of KiCad, one could contribute on the
link:/contribute/docs-team/[documentation], 
link:/contribute/librarians/[libraries]
or actual code contributions to the codebase.

=== Starter Patches

If you are new to software development you might want to look into the following bugs:

* link:https://bugs.launchpad.net/kicad/+bug/1423515[`Bug# 1423515`]
* link:https://bugs.launchpad.net/kicad/+bug/1428125[`Bug# 1428125`]
* link:https://bugs.launchpad.net/kicad/+bug/1395442[`Bug# 1395442`]
* link:https://bugs.launchpad.net/kicad/+bug/1412628[`Bug# 1412628`]
* link:https://bugs.launchpad.net/kicad/+bug/1448460[`Bug# 1448460`]
* link:https://bugs.launchpad.net/kicad/+bug/1424003[`Bug# 1424003`]

Or for example if you are an OS X guy, you might want to filter the bug tracker results as:

* link:https://bugs.launchpad.net/kicad/+bugs?field.searchtext=&orderby=-date_last_updated&search=Search&field.status%3Alist=NEW&field.status%3Alist=CONFIRMED&field.status%3Alist=TRIAGED&field.status%3Alist=INPROGRESS&field.status%3Alist=INCOMPLETE_WITH_RESPONSE&assignee_option=any&field.assignee=&field.bug_reporter=&field.bug_commenter=&field.subscriber=&field.structural_subscriber=&field.tag=osx&field.tags_combinator=ANY&field.has_cve.used=&field.omit_dupes.used=&field.omit_dupes=on&field.affects_me.used=&field.has_patch.used=&field.has_branches.used=&field.has_branches=on&field.has_no_branches.used=&field.has_no_branches=on&field.has_blueprints.used=&field.has_blueprints=on&field.has_no_blueprints.used=&field.has_no_blueprints=on[`Bugs tagged osx that needs attention`]

=== Submitting Patches

Patches are currently submitted and handled via the
link:https://lists.launchpad.net/kicad-developers/[developer mailing list],
where you have to apply for membership to be able to send to it. Or you can attach patches to bug reports.

=== Translating GUI and Docs

If you are the kind guy wanting to help improving kicad by internationalizing it, you should probably have a look at the 
link:http://ci.kicad-pcb.org/job/any-kicad-doc-head/lastSuccessfulBuild/artifact/src/GUI_Translation_HOWTO/GUI_Translation_HOWTO.html[GUI translating howto]. +
Also you are encouraged to contribute to the 
link:/contribute/docs-team/[KiCad Documentation]

=== Contribute to the Official Libraries

If you wish to contribute eeschema, pcbnew or 3dviewer libraries, please see the link:/contribute/librarians/[Librarians] page.

=== Internet Relay Chat (_IRC_)

Feel free to join the IRC channel at irc://irc.freenode.net/#kicad[#kicad@freenode]. A nice bunch of people are casually hanging around in there, so if you have any questions, that I don't know where to ask, you should try asking in here. There are all kinds of people in all kinds of time zones, people who patches kicad and plain enthusiastic users.
